import { hashSync } from 'bcrypt-ts-edge';

const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@google.com',
      password: hashSync('password', 10),
      role: 'admin'
    },
    {
      name: 'Bob',
      email: 'user@google.com',
      password: hashSync('password', 10),
      role: 'user'
    },
  ],

  products: [
    {
      name: 'Haglöfs Tight Medium Backpack',
      slug: 'haglofs-tight-medium-backpack',
      category: "bags",
      description: 'Classic Haglöfs Tight backpack',
      images: [
        '/images/sample-products/haglofs-tight-medium.jpeg',
        '/images/sample-products/haglofs-tight-medium-2.jpeg',
        '/images/sample-products/haglofs-tight-medium-3.jpeg',
      ],
      price: 159.99,
      brand: 'Haglöfs',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Arcteryx Rush Jacket Men's",
      slug: 'arcteryx-rush-jacket-mens',
      category: "Men's Jackets",
      description: 'Timeless style and premium comfort',
      images: [
        '/images/sample-products/arcteryx-rush-jacket-herr.jpeg',
        '/images/sample-products/arcteryx-rush-jacket-herr-2.jpeg',
      ],
      price: 485.9,
      brand: 'Arcteryx',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Adidas Team19 Jacket Men's",
      slug: 'adidas-team19-jacket-mens',
      category: "Men's Jackets",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        '/images/sample-products/adidas-team19-jacket-herr.jpeg',
        '/images/sample-products/adidas-team19-jacket-herr-2.jpeg',
      ],
      price: 199.95,
      brand: 'Adidas',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Fjäll Räven Lush Logo T-Shirt',
      slug: 'fjall-raven-lush-logo-t-shirt',
      category: "Women's T-Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        '/images/sample-products/fjallraven-lush-logo-t-shirt-dam.jpeg',
        '/images/sample-products/fjallraven-lush-logo-t-shirt-dam-2.jpeg',
      ],
      price: 79.95,
      brand: 'Fjäll Räven',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "New Balance 515 Shoes Men's",
      slug: 'new-balance-515-shoes-mens',
      category: "Men's Shoes",
      description: 'Iconic design with refined oxford fabric',
      images: [
        '/images/sample-products/new-balance-515-herr.jpeg',
        '/images/sample-products/new-balance-515-herr-2.jpeg',
      ],
      price: 79.99,
      brand: 'New Balance',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Salomon Xa Pro 3d Shoes Men's",
      slug: 'salomon-xa-pro-3d-shoes-mens',
      category: "Men's Shoes",
      description: 'Iconic design with refined oxford fabric',
      images: [
        '/images/sample-products/salomon-xa-pro-3d-v9-herr.jpeg',
        '/images/sample-products/salomon-xa-pro-3d-v9-herr-2.jpeg',
        '/images/sample-products/salomon-xa-pro-3d-v9-herr-3.jpeg',
      ],
      price: 179.99,
      brand: 'Salomon',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Patagonia Retro Pile Jacket',
      slug: 'patagonia-retro-pile-jacket',
      category: "Men's Jackets",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        '/images/sample-products/patagonia-retro-pile-jacket-herr.jpeg',
      ],
      price: 299.99,
      brand: 'Patagonia',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
